apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: testapp
  name: testapp
spec:
  ports:
  - name: 80-80
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: testapp
  type: NodePort
status:
  loadBalancer: {}
